CREATE TABLE USERS
(
    id   BIGINT      NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE GAME
(
    id          BIGINT   NOT NULL AUTO_INCREMENT,
    trial_count INT      NOT NULL,
    created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE POSITION
(
    id       BIGINT NOT NULL AUTO_INCREMENT,
    game_id  BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    position INT    NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE WINNER
(
    id       BIGINT NOT NULL AUTO_INCREMENT,
    game_id  BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);